### ISSUE TITLE
How do you run docker on pepper in the first place?

### ISSUE THREAD

**Issue by warp1337** [awesomebytes/pepper_os#1]
See above mate :)

**Comment by awesomebytes** [comment]
Short answer: you can't.

Long answer: instead of using containers I compile a 'full OS' called
Gentoo Prefix. I've setup CI and I'm waiting for resources to setup CD so
all the SW up to a lot of ROS and a bunch of other useful SW is deployable.
The installation is just extracting a folder. This package aims to automate
the building of the specific bits for Pepper. (Mainly an open source &
cleaner reimplementation of what I had).
The base image is the real image of the robot so to not have deployment
surprises.

WIP!
